### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by eduardoaraya** [dbinclui-org/dbinclui-frontend#63]
Alterem a inserção do valor de file para pegar apenas a string com o nome ao invés de inserir um elemento JSX diretamente.
Criem a interação do mesmo adicionando as `keys`.

[Arquivo](https://github.com/dbinclui-org/dbinclui-frontend/blob/develop/src/pages/register-digital-content/index.tsx#L55)
```ts
 <input
    data-testid="inputFile"
    accept="image/*,.pdf,.doc, .docx"
    type="file"
    hidden
    multiple
    onChange={(event: any) => {
      file.push(event.target.files[0].name);
      setFile([...file]);
    }}
  />
</Button>
{file.length !== 0 ? (
  file.map((item, index) => (
      <Typography key={index} sx={styles.fileName}>
          {item}
      </Typography>
  ))
) : (
  <Typography sx={styles.fileName}>
    Nenhum arquivo selecionado
  </Typography>
)}
```

**Comment by nickolasL13** [comment]
Não está mais dessa maneira, a gente já alterou. Pode verificar na branch feature/DBI-US011-60

**Comment by eduardoaraya** [comment]
@nickolasL13  Depois que for feita a PR link esta issue

**Comment by nickolasL13** [comment]
Beleza

**Comment by nickolasL13** [comment]
@eduardoaraya Depois verifica na branch para ver se está correto como a gente deixou. Provavelmente vai mudar um pouco, mas a ideia e ficar mais ou menos daquele jeito
